framework:
    messenger:
        default_bus: messenger.bus.default
        buses:
            messenger.bus.default: ~

        transports:
            sync: 'sync://'

            async:
                dsn: 'doctrine://default'

        routing:

            'App\Application\Cart\Command\AddItemToCartCommand': sync
            'App\Application\Cart\Command\CreateCartCommand': sync
            'App\Application\Cart\Command\RemoveItemFromCartCommand': sync
            'App\Application\Cart\Command\UpdateCartCommand': sync
            'App\Application\Cart\Command\UpdateItemFromCartCommand': sync

            'App\Domain\Cart\Events\CartCheckoutEvent': async
