# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'
        autowire: true
        autoconfigure: true

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\Application\Cart\Command\AddItemToCartCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\Application\Cart\Command\CreateCartCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\Application\Cart\Command\CheckoutCartCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\Application\Cart\Command\RemoveItemFromCartCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\Application\Cart\Command\UpdateItemFromCartCommandHandler:
        tags: [ 'messenger.message_handler' ]

    App\Infrastructure\Cart\Symfony\Controller\:
        resource: '../src/Infrastructure/Cart/Symfony/Controller/'
        tags: ['controller.service_arguments']

